extensions:
  health_check:
    endpoint: "${SPLUNK_LISTEN_INTERFACE}:13133"
  http_forwarder:
    ingress:
      endpoint: "${SPLUNK_LISTEN_INTERFACE}:6060"
    egress:
      endpoint: "${SPLUNK_API_URL}"
      # Use instead when sending to gateway
      # endpoint: "${SPLUNK_GATEWAY_URL}"
  smartagent:
    bundleDir: "${SPLUNK_BUNDLE_DIR}"
    collectd:
      configDir: "${SPLUNK_COLLECTD_DIR}"
  zpages:
    endpoint: "${SPLUNK_LISTEN_INTERFACE}:55679"

receivers:
  hostmetrics:
    collection_interval: 1s
    scrapers:
      cpu:
      disk:
      filesystem:
      memory:
      network:
      # System load average metrics https://en.wikipedia.org/wiki/Load_(computing)
      load:
      # Paging/Swap space utilization and I/O metrics
      paging:
      # Aggregated system process count metrics
      processes:
      # System processes metrics, disabled by default
      # process:

  jaeger:
    protocols:
      grpc:
        endpoint: 0.0.0.0:14250
      thrift_binary:
        endpoint: 0.0.0.0:6832
      thrift_compact:
        endpoint: 0.0.0.0:6831
      thrift_http:
        endpoint: 0.0.0.0:14268

  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
      
  # This section is used to collect the OpenTelemetry Collector metrics
  # Even if just a Splunk APM customer, these metrics are included
  prometheus/internal:
    config:
      scrape_configs:
      - job_name: 'otel-collector'
        scrape_interval: 10s
        static_configs:
        - targets: ["${SPLUNK_LISTEN_INTERFACE}:8888"]
        metric_relabel_configs:
          - source_labels: [ __name__ ]
            regex: 'otelcol_rpc_.*'
            action: drop
          - source_labels: [ __name__ ]
            regex: 'otelcol_http_.*'
            action: drop
          - source_labels: [ __name__ ]
            regex: 'otelcol_processor_batch_.*'
            action: drop
  
  smartagent/signalfx-forwarder:
    type: signalfx-forwarder
    listenAddress: "${SPLUNK_LISTEN_INTERFACE}:9080"
  
  smartagent/processlist:
    type: processlist

  signalfx:
    endpoint: "${SPLUNK_LISTEN_INTERFACE}:9943"
    # Whether to preserve incoming access token and use instead of exporter token
    # default = false
    #access_token_passthrough: true
    
  zipkin:
    endpoint: "${SPLUNK_LISTEN_INTERFACE}:9411"
  
  smartagent/win_services:
    type: telegraf/win_services
    intervalSeconds: 1
    serviceNames:
      - Dnscache
      - Dhcp
      - LanmanServer
      - LanmanWorkstation
      - SessionEnv
      - EventLog
      - lmhosts
      - PlugPlay
      - RpcEptMapper
      - MSDTC
      - SamSs

  smartagent/procstat-docker:
    type: telegraf/procstat
    intervalSeconds: 1
    exe: dockerd.exe
    pattern: docker
    WinService: docker

  smartagent/procstat-otel:
    type: telegraf/procstat
    intervalSeconds: 1
    exe: otelcol.exe
    pattern: otel
    WinService: splunk-otel-collector

  smartagent/telegraf/win_perf_counters:
    type: telegraf/win_perf_counters
    printValid: true
    counterRefreshInterval: 10
    objects:
     - objectName: "Processor"
       instances:
        - "*"
       counters:
        - "% Idle Time"
        - "% Interrupt Time"
        - "% Privileged Time"
        - "% User Time"
        - "% Processor Time"
       includeTotal: true
       measurement: "win_cpu"

     - objectName: "PhysicalDisk"
       instances:
        - "*"
       counters:
        - "% Disk Read Time"
        - "% Disk Write Time"
        - "% Idle Time"
       includeTotal: false
       measurement: "win_disk"

  smartagent/ntp:
    type: ntp
    host: pool.ntp.org

processors:
  batch:
  # Enabling the memory_limiter is strongly recommended for every pipeline.
  # Configuration is based on the amount of memory allocated to the collector.
  # For more information about memory limiter, see
  # https://github.com/open-telemetry/opentelemetry-collector/blob/main/processor/memorylimiter/README.md
  memory_limiter:
    check_interval: 2s
    limit_mib: ${SPLUNK_MEMORY_LIMIT_MIB}

  # Detect if the collector is running on a cloud system, which is important for creating unique cloud provider dimensions.
  # Detector order is important: the `system` detector goes last so it can't preclude cloud detectors from setting host/os info.
  # Resource detection processor is configured to override all host and cloud attributes because instrumentation
  # libraries can send wrong values from container environments.
  # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/resourcedetectionprocessor#ordering
  resourcedetection:
    detectors: [gcp, ecs, ec2, azure, system]
    override: true

  # Optional: The following processor can be used to add a default "deployment.environment" attribute to the logs and 
  # traces when it's not populated by instrumentation libraries.
  # If enabled, make sure to enable this processor in the pipeline below.
  #resource/add_environment:
    #attributes:
      #- action: insert
        #value: staging/production/...
        #key: deployment.environment

exporters:
  # Send to gateway
  otlphttp:
    endpoint: http://${SPLUNK_GATEWAY_URL}:4318
  otlp:
    endpoint: "${SPLUNK_GATEWAY_URL}:4317"
    tls:
      insecure: true

  # Traces
  sapm:
    access_token: "${SPLUNK_ACCESS_TOKEN}"
    endpoint: "${SPLUNK_TRACE_URL}"

  # Metrics + Events
  signalfx:
    access_token: "${SPLUNK_ACCESS_TOKEN}"
    api_url: "${SPLUNK_API_URL}"
    ingest_url: "${SPLUNK_INGEST_URL}"
    # Use instead when sending to gateway
    # api_url: http://${SPLUNK_GATEWAY_URL}:6060
    # ingest_url: http://${SPLUNK_GATEWAY_URL}:9943
    sync_host_metadata: true
    correlation:

  # Logs
  splunk_hec:
    token: "${SPLUNK_HEC_TOKEN}"
    endpoint: "${SPLUNK_HEC_URL}"
    source: "otel"
    sourcetype: "otel"
    profiling_data_enabled: false

  # Profiling
  splunk_hec/profiling:
    token: "${SPLUNK_ACCESS_TOKEN}"
    endpoint: "${SPLUNK_INGEST_URL}/v1/log"
    log_data_enabled: false

  # Debug
  debug:
    verbosity: detailed

service:
  telemetry:
    metrics:
      address: "${SPLUNK_LISTEN_INTERFACE}:8888"

  extensions:
  - health_check
  - http_forwarder
  #- zpages
  - smartagent

  pipelines:
    traces:
      receivers:
      - jaeger
      - otlp
      - smartagent/signalfx-forwarder
      - zipkin
      processors:
      - memory_limiter
      - batch
      - resourcedetection
      #- resource/add_environment
      exporters:
      - sapm
      - signalfx
      # Use instead when sending to gateway
      # - otlphttp
      # - signalfx

    metrics:
      receivers:
      - hostmetrics
      - otlp
      - signalfx
      - smartagent/signalfx-forwarder
      - smartagent/win_services
      - smartagent/procstat-docker
      - smartagent/procstat-otel
      - smartagent/telegraf/win_perf_counters
      - smartagent/ntp
      processors:
      - memory_limiter
      - batch
      - resourcedetection
      exporters:
      - signalfx
    
    metrics/internal:
      receivers:
      - prometheus/internal
      processors:
      - memory_limiter
      - batch
      - resourcedetection
      exporters:
      - signalfx
    
    logs/signalfx:
      receivers:
      - signalfx
      - smartagent/processlist
      processors:
      - memory_limiter
      - batch
      - resourcedetection
      exporters:
      - signalfx
    
    logs:
      receivers:
      - otlp
      processors:
      - memory_limiter
      - batch
      - resourcedetection
      #- resource/add_environment
      exporters:
      - splunk_hec
      - splunk_hec/profiling